name: Spice Grinder Scan & Upload

description: Clones or copies input, runs Spice Grinder scan, then uploads results

inputs:
  file_path:
    description: Path to local files to scan
    required: false
    default: ""
  config:
    description: Path to config file inside container
    required: true
  mode:
    description: Upload mode (e.g. public, private)
    required: true
  jwt:
    description: Grinder JWT token
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare input/output directories
      shell: bash
      run: mkdir -p target/input target/output

    - name: Copy input from path
      if: ${{ inputs.file_path != '' }}
      shell: bash
      run: |
        cp -r ${{ inputs.file_path }}/* target/input/

    - name: Scan with Spice Grinder
      shell: bash
      run: |
        docker run --platform linux/amd64 --rm --network none --user $(id -u):$(id -g) \
        -v "$(pwd)/target/input:/input:ro" -v "$(pwd)/target/output:/output" spicelabs/grinder:latest \
        -c "${{ inputs.config }}" -b /input -o /output

    - name: Upload with Spice Grinder
      shell: bash
      run: |
        docker run --platform linux/amd64 --rm --user $(id -u):$(id -g) \
        -v "$(pwd)/target/output:/output" spicelabs/grinder:latest \
        -c upload -p /output \
        -j "${{ inputs.jwt }}" \
        -m "${{ inputs.mode }}"
