name: Spice Grinder Scan & Upload

description: Clones or copies input, runs Spice Grinder scan, then uploads results

inputs:
  file_path:
    description: Path to local files to scan
    required: false
    default: .
  token: 
    description: Spice Pass JWT
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Spice Grinder
      shell: bash
      run: |
        set -x
        mkdir -p target/input target/output
        find ${{ inputs.file_path }}
        docker run --platform linux/amd64 --quiet --rm --network none --user $(id -u):$(id -g) \
        -v "${{ inputs.file_path }}:/input:ro" -v "$(pwd)/target/output:/output" "spicelabs/grinder:latest" \
        -c adg -b /input -o /output
        docker run --platform linux/amd64 --quiet --rm --user $(id -u):$(id -g) \
        -v "$(pwd)/target/output:/output" spicelabs/grinder:latest \
        -c upload -p /output \
        -j ${{ inputs.token }} \
        -m bt
        
