name: Test Check Cargo Version Matches Tag Action

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Create Cargo.toml for testing
        run: |
          mkdir -p test_project
          cd test_project
          echo '[package]' > Cargo.toml
          echo 'name = "test_project"' >> Cargo.toml
          echo 'version = "1.2.3"' >> Cargo.toml
          cd ..

      - name: Create initial commit
        run: |
          git add .
          git commit -m "Initial commit for testing"
          git push origin main

      - name: Set up Git configuration
        run: |
          git config user.name --global "SpicyGrzl"
          git config user.email --global "spicygrzl@spicelabs.io"

      - name: Create Git tag v1.2.3 for testing
        run: |
          git tag v1.2.3
          git push https://${{ secrets.GH_USERNAME_SG }}:${{ secrets.GH_TOKEN }}@github.com/spice-labs-inc/cargo-version-check.git v1.2.3

      - name: Run Check Cargo Version Matches Tag action
        uses: ./.github/actions/check-cargo-version

